#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p res-gpu-large
#SBATCH --qos=long-high-prio
#SBATCH --job-name=hetvae
#SBATCH --output="MCG+08-11-011_g%j.out"
#SBATCH -t 150:00:0

source /etc/profile
source activate $HOME/miniconda/envs/hetvae

python3 $HOME/astr/hetast/src/train.py data_folder=datasets/ZTF_MCG+08-11-011_g \
                                       checkpoint=datasets/ZTF_g1.1252859830856323.h5 \
                                       training.optimizer.lr=0.0001 \
                                       dataset.start_col=1 \
                                       dataset.sep=comma \
                                       dataset.shuffle=false \
                                       training.scheduler.reset=true \
                                       fixed.num_resamples=12 \
                                       save_at=400 \
                                       training.niters=100000 \
                                       print_at=100 \
                                       training.loss.kl_annealing=false \
                                       filter.min_length=0 \
                                       filter.keep_missing=True