#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p res-gpu-large
#SBATCH --qos=long-high-prio
#SBATCH --job-name=hetvae
#SBATCH --output="intrpz%j.out"
#SBATCH -t 150:00:0

source /etc/profile
source activate $HOME/miniconda/envs/hetvae

python3 $HOME/astr/hetast/src/intrp.py 