#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p res-gpu-large
#SBATCH --qos=long-high-prio
#SBATCH --job-name=hetvae
#SBATCH --output="mrk142%j.out"
#SBATCH -t 150:00:0

source /etc/profile
source activate $HOME/miniconda/envs/hetvae

python3 $HOME/astr/hetast/src/train.py data_folder=datasets/ZTF_Mrk142 \
                                       checkpoint=datasets/ZTF_gri0.8933992385864258.h5 \
                                       training.optimizer.lr=0.0001 \
                                       dataset.start_col=1 \
                                       dataset.sep=comma \
                                       dataset.shuffle=false \
                                       fixed.num_resamples=12 \
                                       training.optimizer.scheduler=false \
                                       save_at=2000 \
                                       training.niters=100000 \
                                       print_at=100 \
                                       training.loss.kl_annealing=false \
                                       filter.min_length=1