#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p res-gpu-large
#SBATCH --qos=long-high-prio
#SBATCH --job-name=hetvae
#SBATCH --output="jsg%j.out"
#SBATCH -t 150:00:00

source /etc/profile
source activate $HOME/miniconda/envs/hetvae

python3 $HOME/astr/hetast/src/train.py data_folder=datasets/ZTF_g_test training.regularization.dropout=0.1
