#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p res-gpu-large
#SBATCH --qos=long-low-prio
#SBATCH --job-name=hetvae
#SBATCH --output="jsr%j.out"
#SBATCH -t 150:00:00

source /etc/profile
source activate $HOME/miniconda/envs/hetvae

python3 $HOME/astr/hetast/src/train2.py \
    --data-folder datasets/ZTF_r \
    --device cuda \
    --batch-size 2 \
    --niters 20000 \
    --start-col 1 \
    --save-at 30 \
    --enc-num-heads 16 \
    --latent-dim 64 \
    --n-union-tp 3500 \
    --lr 0.00000001 \
    --checkpoint datasets/ZTF_r0.7257919311523438.h5 \
    --kl-annealing \
    --num-ref-points 16 \
    --print-at 1 \
    --frac 0.5 \
    --num-resamples 0
