#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p res-gpu-large
#SBATCH --qos=long-high-prio
#SBATCH --job-name=hetvae
#SBATCH --output="r-%j.out"
#SBATCH -t 20:00:00

source /etc/profile
source $HOME/miniconda/bin/activate
source activate $HOME/miniconda/envs/hetvae

python3 $HOME/astr/hetast/src/train.py \
    --data-folder datasets/ZTF_rband \
    --device cuda \
    --batch-size 256 \
    --niters 3000 \
    --start-col 1 \
    --save-at 10 \
    --kl-annealing \
    --enc-num-heads 16 \
    --latent-dim 64 \
    --lr 0.0002 \
    --num-ref-points 16 \
    --print-at 1 \
    --frac 0.5 \
    --num-resamples 10
