#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p res-gpu-large
#SBATCH --qos=long-high-prio
#SBATCH --job-name=hetvae
#SBATCH --output="test_loss-%j.out"
#SBATCH -t 10:00:00

source /etc/profile
source activate $HOME/miniconda/envs/hetvae

# args are: data_folder, checkpoint, num samples

python3 $HOME/astr/hetast/src/test_loss.py \
    ./datasets/ZTF_gband_test \
    ./ZTFgr_small0.915856122970581.h5 \
    10