#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p res-gpu-large
#SBATCH --qos=long-high-prio
#SBATCH --job-name=hetvae
#SBATCH --output="train-%j.out"
#SBATCH -t 10:00:00

source /etc/profile
source activate $HOME/miniconda/envs/hetvae

python3 $HOME/astr/hetast/src/train.py \
    --data-folder datasets/ZTF_gband_test \
    --device mps \
    --niters 10 \
    --start-col 1 \
    --save-at 1000 \
    --bound-variance \
    --kl-annealing \
    --lr 0.001 \
    --print-at 10 \
    --frac 0.9