## default 

# ${dataset}_${model} referencing chosen vals


defaults:
    - _self_

data_folder: ./datasets/ZTF_g
        
start_col: 1
checkpoint: null
seed: 2
device: cuda

      
model: 
    net: HeTVAE
    mixing: concat
    n_union_tp :  3500
    seed: 2
    size: 
        embed_time :  128
        num_heads :  16
        latent_dim :  64
        num_ref_points: 16
        rec_hidden: 128
        width: 512 
     
training: 
    niters :  6000
    patience :  1000
    batch_size: 2
    k_iwae: 1
    optimizer: 
        lr :  0.0003
        beta1 :  0.9
        beta2: 0.999
        scheduler :  true
        warmup :  10    
    scheduler: 
        factor: 0.9
        lr_patience: 35
        threshold: 0.01   
    regularization: 
        dropout: 0.1
    loss: 
        inc_errors: false
        frac: 0.5
        mse_weight: 10.0
        kl_annealing: true
    kl:
        kl_itrs: 6000
        n_cycles: 32
        start: 0.0
        stop: 0.1
        ratio: 0.5
        
filter:
    keep_missing: false
    min_length: 25

print_at:  1
save_at:  30

fixed: 
    kl_zero: false
    const_var: false
    var_per_dim: false
    num_resamples : 0
    is_bounded: false
    
    
    
