## default 

# ${dataset}_${model} referencing chosen vals


defaults:
    - _self_

data_folder: ZTF_g
        
start_col: 1
checkpoint: null
seed: 2
      
model: 
    net: HeTVAE
    mixing: concat
    n_union_tp :  3500
    seed: 2
    size: 
        embed_time :  128
        num_heads :  16
        latent_dim :  128
        num_ref_points: 16
        rec_hidden: 128
        width: 512 
     
training: 
    niters :  6000
    patience :  1000
    batch_size: 2
    device: mps
    k_iwae: 1
    optimizer: 
        lr :  0.001
        beta1 :  0.9
        beta2: 0.999
        scheduler :  true
        warmup :  10    
    scheduler: 
        factor: 0.5
        lr_patience: 30
        threshold: 0.01   
    regularization: 
        dropout: 0.0    
    loss: 
        inc_errors: false
        frac: 0.5
        mse_weight: 5.0
        kl_annealing: true

print_at:  1
save_at:  1000

fixed: 
    kl_zero: false
    const_var: false
    var_per_dim: false
    std: 0.1
    num_resamples : 0
    
    
    
